version: '2.3'

services:
  sova-tts-gpu:
    #restart: always
    container_name: sova-tts-gpu
    #build:
    #  context: .
    #  dockerfile: Dockerfile.gpu
    runtime: nvidia
    image: aspichakou/sova-tts-aio-gpu
    #volumes:
    #  - .:/sova-tts
    ports:
      - 8809:8899

  sova-tts:
    #restart: always
    container_name: sova-tts
    #build:
    #  context: .
    #  dockerfile: Dockerfile.cpu
    image: aspichakou/sova-tts-aio
    #volumes:
    #  - .:/sova-tts
    ports:
      - 8899:8899
